### ISSUE TITLE
5.0.12 error

### ISSUE THREAD

**Issue by boboldehampsink** [solspace/craft3-calendar#347]
When updating from 5.0.11 to 5.0.12 I see the following error:

```

Exception 'ArgumentCountError' with message 'Too few arguments to function PHPStan\PhpDocParser\Lexer\Lexer::__construct(), 0 passed in /app/user/vendor/symfony/type-info/TypeResolver/StringTypeResolver.php on line 66 and exactly 1 expected'
--
  | 2024-11-13 00:12:09 UTC |  
  | 2024-11-13 00:12:09 UTC | in /app/user/vendor/phpstan/phpdoc-parser/src/Lexer/Lexer.php:102
  | 2024-11-13 00:12:09 UTC |  
  | 2024-11-13 00:12:09 UTC | Stack trace:
  | 2024-11-13 00:12:09 UTC | #0 /app/user/vendor/symfony/type-info/TypeResolver/StringTypeResolver.php(66): PHPStan\PhpDocParser\Lexer\Lexer->__construct()
  | 2024-11-13 00:12:09 UTC | #1 /app/user/vendor/symfony/type-info/TypeResolver/TypeResolver.php(71): Symfony\Component\TypeInfo\TypeResolver\StringTypeResolver->__construct()
  | 2024-11-13 00:12:09 UTC | #2 /app/user/vendor/symfony/type-info/TypeResolver/TypeResolver.php(66): Psr\Container\ContainerInterface@anonymous->__construct()
  | 2024-11-13 00:12:09 UTC | #3 /app/user/vendor/symfony/property-info/Extractor/ReflectionExtractor.php(102): Symfony\Component\TypeInfo\TypeResolver\TypeResolver::create()
  | 2024-11-13 00:12:09 UTC | #4 /app/user/vendor/symfony/property-access/PropertyAccessor.php(91): Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor->__construct(Array, NULL, NULL, false)
  | 2024-11-13 00:12:09 UTC | #5 /app/user/vendor/solspace/craft-calendar/packages/plugin/src/Elements/Event.php(313): Symfony\Component\PropertyAccess\PropertyAccessor->__construct()
  | 2024-11-13 00:12:09 UTC | #6 /app/user/vendor/solspace/craft-calendar/packages/plugin/src/Services/EventsService.php(106): Solspace\Calendar\Elements\Event::buildQuery(Array)
  | 2024-11-13 00:12:09 UTC | #7 /app/user/vendor/solspace/craft-calendar/packages/plugin/src/Services/ViewDataService.php(74): Solspace\Calendar\Services\EventsService->getEventQuery(Array)
  | 2024-11-13 00:12:09 UTC | #8 /app/user/vendor/solspace/craft-calendar/packages/plugin/src/Services/ViewDataService.php(43): Solspace\Calendar\Services\ViewDataService->getEventQuery(Object(Solspace\Calendar\Library\Duration\WeekDuration), Array)
  | 2024-11-13 00:12:09 UTC | #9 /app/user/fixtures/data/events.php(8): Solspace\Calendar\Services\ViewDataService->getWeek(Array)


```

**Comment by kjmartens** [comment]
Hi @boboldehampsink,

It looks like Symfony corrected this issue a few hours ago on their end. Can you run composer update again and see if it resolves the issue? 🙂

**Comment by boboldehampsink** [comment]
@kjmartens that did the trick!
